spring:
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import: "optional:configserver:http://localhost:8888/"
